#!/bin/bash

# Install atau upgrade dependencies dari requirements.txt
echo "Menginstal atau mengupgrade dependencies..."
pip install --upgrade -r requirements.txt

# Meminta input untuk mengisi data pada sample.env
echo "Silakan isi data berikut:"

read -p "API_ID: " API_ID
read -p "API_HASH: " API_HASH
read -p "BOT_TOKEN: " BOT_TOKEN
read -p "OWNER_ID: " OWNER_ID
read -p "SAWERIA_EMAIL: " SAWERIA_EMAIL
read -p "SAWERIA_PASSWORD: " SAWERIA_PASSWORD
read -p "MONGO_URI: " MONGO_URI
read -p "CHANNEL_DB: " CHANNEL_DB

# Menulis data ke file .env
echo "Membuat file .env..."
cat <<EOL > .env
API_ID=$API_ID
API_HASH=$API_HASH
BOT_TOKEN=$BOT_TOKEN
OWNER_ID=$OWNER_ID
SAWERIA_EMAIL=$SAWERIA_EMAIL
SAWERIA_PASSWORD=$SAWERIA_PASSWORD
MONGO_URI=$MONGO_URI
CHANNEL_DB=$CHANNEL_DB
EOL

echo "Setup selesai! File .env telah dibuat."
